class Commands:
    LEECH = "leech@Tggrive_bot"
    PURGE = "purge@Tggrive_bot"
    PAUSEALL = "pauseall@Tggrive_bot"
    RESUMEALL = "resumeall@Tggrive_bot"
    STATUS = "status@Tggrive_bot"
    SETTINGS = "settings@Tggrive_bot"
    EXEC = "exec@Tggrive_bot"
    UPLOAD = "upload@Tggrive_bot"
    YTDL = "ytdl@Tggrive_bot"
    PYTDL = "pytdl@Tggrive_bot"
    ABOUT = "about@Tggrive_bot"
    GETLOGS = "getlogs@Tggrive_bot"
    SERVER = "server@Tggrive_bot"
    USERSETTINGS = "usetting@Tggrive_bot"
    INSTADL = "instadl@Tggrive_bot"
